# Generated by Django 4.1.7 on 2023-03-30 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChargePoint",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Available", "Available"),
                            ("Preparing", "Preparing"),
                            ("Charging", "Charging"),
                            ("SuspendedEVSE", "SuspendedEVSE"),
                            ("SuspendedEV", "SuspendedEV"),
                            ("Finishing", "Finishing"),
                            ("Reserved", "Reserved"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Available", "Available"),
                            ("Preparing", "Preparing"),
                            ("Charging", "Charging"),
                            ("SuspendedEVSE", "SuspendedEVSE"),
                            ("SuspendedEV", "SuspendedEV"),
                            ("Finishing", "Finishing"),
                            ("Reserved", "Reserved"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                ("is_connected", models.BooleanField(default=False)),
                (
                    "vendor_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "vendor_status_info",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "vendor_status_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("ws_queue", models.CharField(blank=True, default="", max_length=256)),
                ("hw_vendor", models.CharField(blank=True, default="", max_length=256)),
                ("hw_model", models.CharField(blank=True, default="", max_length=256)),
                ("hw_serial", models.CharField(blank=True, default="", max_length=256)),
                (
                    "hw_firmware",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("last_heartbeat_at", models.DateTimeField(null=True)),
                ("last_boot_at", models.DateTimeField(null=True)),
                ("last_connect_at", models.DateTimeField(null=True)),
                ("last_tx_start_at", models.DateTimeField(null=True)),
                ("last_tx_stop_at", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebsocketEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("connect", "connect"),
                            ("disconnect", "disconnect"),
                            ("receive", "receive"),
                        ],
                        max_length=64,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "charge_point",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ocpp.chargepoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(null=True)),
                ("stopped_at", models.DateTimeField(null=True)),
                ("remote_started_at", models.DateTimeField(null=True)),
                ("remote_stopped_at", models.DateTimeField(null=True)),
                ("connector_id", models.CharField(max_length=64)),
                ("id_tag", models.CharField(max_length=256)),
                ("meter_start", models.IntegerField(default=0)),
                ("meter_stop", models.IntegerField(default=0)),
                (
                    "stop_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EmergencyStop", "EmergencyStop"),
                            ("EVDisconnected", "EVDisconnected"),
                            ("HardReset", "HardReset"),
                            ("Local", "Local"),
                            ("Other", "Other"),
                            ("PowerLoss", "PowerLoss"),
                            ("Reboot", "Reboot"),
                            ("SoftReset", "SoftReset"),
                            ("UnlockCommand", "UnlockCommand"),
                            ("DeAuthorized", "DeAuthorized"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "charge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ocpp.chargepoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeterValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("context", models.CharField(max_length=128)),
                ("format", models.CharField(max_length=128)),
                ("location", models.CharField(max_length=128)),
                ("measurand", models.CharField(max_length=128)),
                ("phase", models.CharField(max_length=128)),
                ("unit", models.CharField(max_length=16)),
                ("value", models.FloatField()),
                ("is_final", models.BooleanField(default=False)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ocpp.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_type", models.IntegerField()),
                ("unique_id", models.CharField(max_length=128)),
                (
                    "actor",
                    models.CharField(
                        choices=[("cp", "cp"), ("cs", "cs")], max_length=64
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Authorize", "Authorize"),
                            ("BootNotification", "BootNotification"),
                            ("CancelReservation", "CancelReservation"),
                            ("ChangeAvailability", "ChangeAvailability"),
                            ("ChangeConfiguration", "ChangeConfiguration"),
                            ("ClearCache", "ClearCache"),
                            ("ClearChargingProfile", "ClearChargingProfile"),
                            ("DataTransfer", "DataTransfer"),
                            (
                                "DiagnosticsStatusNotification",
                                "DiagnosticsStatusNotification",
                            ),
                            (
                                "FirmwareStatusNotification",
                                "FirmwareStatusNotification",
                            ),
                            ("GetCompositeSchedule", "GetCompositeSchedule"),
                            ("GetConfiguration", "GetConfiguration"),
                            ("GetDiagnostics", "GetDiagnostics"),
                            ("GetLocalListVersion", "GetLocalListVersion"),
                            ("Heartbeat", "Heartbeat"),
                            ("MeterValues", "MeterValues"),
                            ("RemoteStartTransaction", "RemoteStartTransaction"),
                            ("RemoteStopTransaction", "RemoteStopTransaction"),
                            ("ReserveNow", "ReserveNow"),
                            ("Reset", "Reset"),
                            ("SendLocalList", "SendLocalList"),
                            ("SetChargingProfile", "SetChargingProfile"),
                            ("StartTransaction", "StartTransaction"),
                            ("StatusNotification", "StatusNotification"),
                            ("StopTransaction", "StopTransaction"),
                            ("TriggerMessage", "TriggerMessage"),
                            ("UnlockConnector", "UnlockConnector"),
                            ("UpdateFirmware", "UpdateFirmware"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                ("data", models.JSONField()),
                (
                    "charge_point",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ocpp.chargepoint",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ocpp.message",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ocpp.transaction",
                    ),
                ),
            ],
            options={
                "unique_together": {("actor", "unique_id")},
            },
        ),
    ]
