# Generated by Django 4.1.7 on 2023-04-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpp", "0002_message_call_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargepoint",
            name="name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
