# Generated by Django 4.1.7 on 2023-04-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocpp", "0004_remove_transaction_remote_started_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargepoint",
            name="hw_iccid",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
