# Generated by Django 4.1.7 on 2023-04-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpp", "0005_chargepoint_hw_iccid"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargepoint",
            name="hw_imsi",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
