# Generated by Django 5.0.1 on 2024-01-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ocpp", "0006_chargepoint_hw_imsi"),
    ]

    operations = [
        migrations.AddField(
            model_name="metervalue",
            name="is_incorrect",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="meter_correction",
            field=models.IntegerField(default=0),
        ),
    ]
